### ISSUE TITLE
Intercepted exceptions from plone.caching should also be ignored by default

### ISSUE THREAD

**Issue by do3cc** [4teamwork/ftw.raven#15]

**Comment by lukasgraf** [comment]
@do3cc could you please give an example of an exception from `plone.caching` that should be ignored, but currently isn't?

**Comment by do3cc** [comment]
https://community.plone.org/t/plone-caching-myriades-of-intercepted-exceptions-after-plone-4-0-4-3-migration/227

**Comment by do3cc** [comment]
Sorry, I got the link before you asked
The Interception exception is called "Intercepted"

```
plone.caching.Intercepted
```

**Comment by jone** [comment]
Makes sense 👍 

`Intercepted` should be added to the default exception classnames: https://github.com/4teamwork/ftw.raven/blob/78122aed3f5b7a51fb5ea36b07dad0336bfa4d58/ftw/raven/config.py#L29
and the README should be updated accordingly: https://github.com/4teamwork/ftw.raven/blob/78122aed3f5b7a51fb5ea36b07dad0336bfa4d58/README.rst#ignored-exceptions

**Comment by lukasgraf** [comment]
Agreed 😉 👍

**Comment by jone** [comment]
@do3cc Released with `ftw.raven = 1.1.3` 🎉
