### ISSUE TITLE
Not working in Plone 5

### ISSUE THREAD

**Issue by pbauer** [4teamwork/ftw.raven#17]
Can we have a version of this that works with Plone 5? The main issues are the resource-registration and plone.app.linkintegrity with was rewritten to no longer monkeypatch the zpublisher_exception_hook

**Comment by pbauer** [comment]
Great, thanks!

**Comment by mbaechtold** [comment]
Please note that we only support the upcoming Plone 5.1.x (which adds back the handling of `jsregistry.xml`), we do not support Plone 5.0.x.
