### ISSUE TITLE
Support for adding custom tags

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/ftw.raven#3]
It would be nice if we could supply user-defined [tags](https://docs.getsentry.com/hosted/clientdev/#tags).

This would for example allow us to sum up a couple staging deployments (DEV, TEST, ...) under the same Sentry project, but distinguish them via the corresponding tags.

From what I can tell, these would need to be included in the [prepared `data` structure here](https://github.com/4teamwork/ftw.raven/blob/08aad5d228da1cf6328a2181949853e9d36acef9/ftw/raven/reporter.py#L28-L31).

**Comment by jone** [comment]
:+1: for custom tag.f
By the way: the URL could tell you on which deployment the error happened :wink:
